### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by justincy** [openplacedatabase/www#5]
This represents our vision for OPD at the point we stopped working on it
- [ ] clear large poly edit line selection when selecting new shape
- [ ] better login
- [ ] 404 page
- [ ] add points/markers for cities
- [ ] enable cutouts for polygons to make donuts
- [ ] add tooltips to buttons
- [ ] view new geojsons after uploading
- [ ] catch exceptions thrown by JSON.parse when uploading
- [ ] when a ring in a polygon gets down to less than 3 points, just delete it
- [ ] add odbl license to snapshot downloads
- [ ] Document environment variables (remember AWS creds as well)
- [ ] add changes.log to .gitignore
- [ ] Get icon/logo for OPD
- [ ] update js sdk to work in browser
- [ ] update www to use js sdk
- [ ] filter out edits when creating snapshot(.json.12341234)
- [ ] handle search errors on map page
- [ ] hush log statement on search that prints es query
- [ ] handle points properly on /map (zoom is broken)
- [ ] clear large poly edit line selection when selecting new shape
- [ ] allow for edit mode to be exited without clicking on empty area of map
